site_name: UnBemEstar
site_description: Sistema de gestão de agendamentos para clínicas de fisioterapia
site_author: Grupo Hopper — FGA0138

theme:
  name: material
  language: pt
  palette:
    primary: ciano
    accent: teal

nav:
  - Home: index.md
  - Arquitetura: arquitetura/Arquitetura.md
  - Visão do Produto: visao/visao.md
  - Templates: templates/index.md